const laptopSpecs= [
    {
      "id": 1,
      "image_url": "https://cdn.electronicscrazy.sg/Productimage/Razer_Blade_Stealth_13_Gaming_Laptop.jpg",
      "Brand": "Razer",
      "Model": "Blade Stealth 13",
      "Laptop_Series": "Gaming",
      "Processor_Brand": "Intel",
      "Processor_Type": "Core i7",
      "Processor_Generation": "11th",
      "CPU_Cache": "12MB",
      "color": "Black",
      "ram": "16GB",
      "RAM_Type": "LPDDR4X",
      "Max_RAM_Support": "32GB",
      "Storage": "512GB SSD",
      "Installed_SSD_Type": "NVMe",
      "Installed_HDD_Type": "None",
      "Storage_Upgrade": "Yes, up to 2TB SSD",
      "Graphics_Chipset": "NVIDIA GeForce GTX 1650",
      "Graphics_Memory": "4GB",
      "Display_Size": "13.3 inch",
      "Display_Type": "OLED",
      "Display_Resolution": "3840x2160",
      "Touch_Screen": "Yes",
      "Display_Refresh_Rate": "60Hz",
      "Brightness": "400 nits",
      "camera": "720p HD",
      "Battery_Capacity": "53.1WHr",
      "Backup_Time": "Up to 10 hours",
      "power_adapter": "65W USB-C",
      "Warranty": "1 Year",
      "price": 1799,
      "description_1": "The Razer Blade Stealth 13 combines powerful performance and sleek design, making it a perfect choice for gamers and professionals.",
      "description_2": "With its stunning 4K OLED display and robust graphics, this ultrabook delivers an exceptional gaming and multimedia experience."
    },
    {
      "id": 2,
      "image_url": "https://dlcdnwebimgs.asus.com/gain/3D241166-0518-4745-B481-D901886BFD14",
      "Brand": "Asus",
      "Model": "ROG Zephyrus G14",
      "Laptop_Series": "Gaming",
      "Processor_Brand": "AMD",
      "Processor_Type": "Ryzen 9",
      "Processor_Generation": "5th",
      "CPU_Cache": "16MB",
      "color": "Moonlight White",
      "ram": "32GB",
      "RAM_Type": "DDR4",
      "Max_RAM_Support": "32GB",
      "Storage": "1TB SSD",
      "Installed_SSD_Type": "NVMe",
      "Installed_HDD_Type": "None",
      "Storage_Upgrade": "No",
      "Graphics_Chipset": "NVIDIA GeForce RTX 3060",
      "Graphics_Memory": "6GB",
      "Display_Size": "14 inch",
      "Display_Type": "IPS",
      "Display_Resolution": "2560x1600",
      "Touch_Screen": "No",
      "Display_Refresh_Rate": "120Hz",
      "Brightness": "300 nits",
      "camera": "720p HD",
      "Battery_Capacity": "76WHr",
      "Backup_Time": "Up to 11 hours",
      "power_adapter": "180W",
      "Warranty": "1 Year",
      "price": 1999,
      "description_1": "The Asus ROG Zephyrus G14 is a compact powerhouse, combining exceptional performance with portability.",
      "description_2": "Featuring a high refresh rate display and top-tier graphics, it is ideal for gamers on the move."
    },
    {
      "id": 3,
      "image_url": "https://computermania-bd.b-cdn.net/wp-content/uploads/Dell-Alienware-X17.jpg",
      "Brand": "Alienware",
      "Model": "X17 R1",
      "Laptop_Series": "Gaming",
      "Processor_Brand": "Intel",
      "Processor_Type": "Core i9",
      "Processor_Generation": "11th",
      "CPU_Cache": "16MB",
      "color": "Lunar Light",
      "ram": "32GB",
      "RAM_Type": "DDR4",
      "Max_RAM_Support": "64GB",
      "Storage": "1TB SSD",
      "Installed_SSD_Type": "NVMe",
      "Installed_HDD_Type": "None",
      "Storage_Upgrade": "Yes, up to 4TB SSD",
      "Graphics_Chipset": "NVIDIA GeForce RTX 3080",
      "Graphics_Memory": "8GB",
      "Display_Size": "17.3 inch",
      "Display_Type": "IPS",
      "Display_Resolution": "3840x2160",
      "Touch_Screen": "Yes",
      "Display_Refresh_Rate": "120Hz",
      "Brightness": "500 nits",
      "camera": "720p HD",
      "Battery_Capacity": "87WHr",
      "Backup_Time": "Up to 6 hours",
      "power_adapter": "240W",
      "Warranty": "1 Year",
      "price": 2999,
      "description_1": "The Alienware X17 R1 offers a blend of cutting-edge technology and stunning design for the ultimate gaming experience.",
      "description_2": "With its large display and high-performance graphics, this laptop is perfect for immersive gaming."
    },
    {
      "id": 4,
      "image_url": "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c05536398.png",
      "Brand": "HP",
      "Model": "Omen 15",
      "Laptop_Series": "Gaming",
      "Processor_Brand": "Intel",
      "Processor_Type": "Core i7",
      "Processor_Generation": "11th",
      "CPU_Cache": "12MB",
      "color": "Shadow Black",
      "ram": "16GB",
      "RAM_Type": "DDR4",
      "Max_RAM_Support": "32GB",
      "Storage": "1TB SSD",
      "Installed_SSD_Type": "NVMe",
      "Installed_HDD_Type": "None",
      "Storage_Upgrade": "Yes, up to 2TB SSD",
      "Graphics_Chipset": "NVIDIA GeForce RTX 3070",
      "Graphics_Memory": "8GB",
      "Display_Size": "15.6 inch",
      "Display_Type": "IPS",
      "Display_Resolution": "2560x1440",
      "Touch_Screen": "No",
      "Display_Refresh_Rate": "165Hz",
      "Brightness": "300 nits",
      "camera": "720p HD",
      "Battery_Capacity": "70WHr",
      "Backup_Time": "Up to 8 hours",
      "power_adapter": "200W",
      "Warranty": "1 Year",
      "price": 1699,
      "description_1": "The HP Omen 15 is designed for gamers who demand high performance and stunning visuals in a portable package.",
      "description_2": "Featuring a fast refresh rate and powerful graphics, this laptop excels in both gaming and productivity."
    },
    {
      "id": 5,
      "image_url": "https://gearjet.com.bd/wp-content/uploads/2020/11/Gigabyte-AERO-15KB-Core-i7-10th-Gen-iGadget-01.jpg",
      "Brand": "Gigabyte",
      "Model": "AERO 15 OLED",
      "Laptop_Series": "Content Creation",
      "Processor_Brand": "AMD",
    "Processor_Type": "Ryzen 9",
    "Processor_Generation": "5th",
      "CPU_Cache": "12MB",
      "color": "Black",
      "ram": "16GB",
      "RAM_Type": "DDR4",
      "Max_RAM_Support": "64GB",
      "Storage": "1TB SSD",
      "Installed_SSD_Type": "NVMe",
      "Installed_HDD_Type": "None",
      "Storage_Upgrade": "Yes, up to 2TB SSD",
      "Graphics_Chipset": "NVIDIA GeForce RTX 3060",
      "Graphics_Memory": "6GB",
      "Display_Size": "15.6 inch",
      "Display_Type": "OLED",
      "Display_Resolution": "3840x2160",
      "Touch_Screen": "Yes",
      "Display_Refresh_Rate": "60Hz",
      "Brightness": "400 nits",
      "camera": "720p HD",
      "Battery_Capacity": "94WHr",
      "Backup_Time": "Up to 10 hours",
      "power_adapter": "230W",
      "Warranty": "1 Year",
      "price": 2499,
      "description_1": "The Gigabyte AERO 15 OLED combines stunning OLED display technology with powerful performance for creators and gamers.",
      "description_2": "With its sleek design and high-quality graphics, it's perfect for demanding tasks and gaming alike."
    },
    {
      "id": 6,
      "image_url": "https://news.lenovo.com/wp-content/uploads/2021/01/Lenovo-Legion-5-Pro_Front_Facing_Left_Stingray-e1610420175506-1024x584.png.webp",
      "Brand": "Lenovo",
      "Model": "Legion 7i",
      "Laptop_Series": "Gaming",
      "Processor_Brand": "Intel",
      "Processor_Type": "Core i9",
      "Processor_Generation": "11th",
      "CPU_Cache": "16MB",
      "color": "Stingray",
      "ram": "32GB",
      "RAM_Type": "DDR4",
      "Max_RAM_Support": "64GB",
      "Storage": "1TB SSD",
      "Installed_SSD_Type": "NVMe",
      "Installed_HDD_Type": "None",
      "Storage_Upgrade": "Yes, up to 2TB SSD",
      "Graphics_Chipset": "NVIDIA GeForce RTX 3080",
      "Graphics_Memory": "10GB",
      "Display_Size": "16 inch",
      "Display_Type": "IPS",
      "Display_Resolution": "2560x1600",
      "Touch_Screen": "No",
      "Display_Refresh_Rate": "165Hz",
      "Brightness": "500 nits",
      "camera": "720p HD",
      "Battery_Capacity": "80WHr",
      "Backup_Time": "Up to 6 hours",
      "power_adapter": "300W",
      "Warranty": "1 Year",
      "price": 2399,
      "description_1": "The Lenovo Legion 7i delivers exceptional gaming performance with its powerful hardware and stunning display.",
      "description_2": "Built for serious gamers, it offers a perfect balance of speed, graphics, and design."
    },
    {
      "id": 7,
      "image_url": "https://ryans.com/storage/products/main/microsoft-surface-laptop-4-11th-gen-intel-core-i7-11634988347.webp",
      "Brand": "Microsoft",
      "Model": "Surface Laptop 4",
      "Laptop_Series": "Ultrabook",
      "Processor_Brand": "Intel",
      "Processor_Type": "Core i7",
      "Processor_Generation": "12th",
      "CPU_Cache": "12MB",
      "color": "Platinum",
      "ram": "16GB",
      "RAM_Type": "LPDDR4X",
      "Max_RAM_Support": "32GB",
      "Storage": "512GB SSD",
      "Installed_SSD_Type": "NVMe",
      "Installed_HDD_Type": "None",
      "Storage_Upgrade": "Yes, up to 1TB SSD",
      "Graphics_Chipset": "Intel Iris Xe",
      "Graphics_Memory": "Integrated",
      "Display_Size": "13.5 inch",
      "Display_Type": "PixelSense",
      "Display_Resolution": "2256x1504",
      "Touch_Screen": "Yes",
      "Display_Refresh_Rate": "60Hz",
      "Brightness": "400 nits",
      "camera": "720p HD",
      "Battery_Capacity": "47.4WHr",
      "Backup_Time": "Up to 11 hours",
      "power_adapter": "65W USB-C",
      "Warranty": "1 Year",
      "price": 1699,
      "description_1": "The Microsoft Surface Laptop 4 combines style, performance, and portability for a seamless computing experience.",
      "description_2": "With a beautiful display and long battery life, it's perfect for both work and entertainment."
    },
    {
      "id": 8,
      "image_url": "https://images.acer.com/is/image/acer/Triton-300-PT315-53-Backliton-Black-01a-1?$Visual-Filter-XL$",
      "Brand": "Acer",
      "Model": "Predator Triton 300",
      "Laptop_Series": "Gaming",
      "Processor_Brand": "AMD",
        "Processor_Type": "Ryzen 7",
        "Processor_Generation": "5th",
      "CPU_Cache": "12MB",
      "color": "Black",
      "ram": "16GB",
      "RAM_Type": "DDR4",
      "Max_RAM_Support": "32GB",
      "Storage": "1TB SSD",
      "Installed_SSD_Type": "NVMe",
      "Installed_HDD_Type": "None",
      "Storage_Upgrade": "Yes, up to 2TB SSD",
      "Graphics_Chipset": "NVIDIA GeForce RTX 3060",
      "Graphics_Memory": "6GB",
      "Display_Size": "15.6 inch",
      "Display_Type": "IPS",
      "Display_Resolution": "1920x1080",
      "Touch_Screen": "No",
      "Display_Refresh_Rate": "144Hz",
      "Brightness": "300 nits",
      "camera": "720p HD",
      "Battery_Capacity": "59WHr",
      "Backup_Time": "Up to 8 hours",
      "power_adapter": "180W",
      "Warranty": "1 Year",
      "price": 1799,
      "description_1": "The Acer Predator Triton 300 is a powerful gaming laptop designed for gamers seeking top-notch performance.",
      "description_2": "With its fast refresh rate and immersive graphics, it's perfect for intense gaming sessions."
    },
    {
      "id": 9,
      "image_url": "https://ryans.com/storage/products/main/dell-xps-13-plus-9320-13th-gen-intel-core-i7-31724233635.webp",
      "Brand": "Dell",
      "Model": "XPS 15",
      "Laptop_Series": "Ultrabook",
      "Processor_Brand": "Intel",
      "Processor_Type": "Core i7",
      "Processor_Generation": "11th",
      "CPU_Cache": "12MB",
      "color": "Silver",
      "ram": "32GB",
      "RAM_Type": "DDR4",
      "Max_RAM_Support": "64GB",
      "Storage": "1TB SSD",
      "Installed_SSD_Type": "NVMe",
      "Installed_HDD_Type": "None",
      "Storage_Upgrade": "Yes, up to 2TB SSD",
      "Graphics_Chipset": "NVIDIA GeForce GTX 1650 Ti",
      "Graphics_Memory": "4GB",
      "Display_Size": "15.6 inch",
      "Display_Type": "OLED",
      "Display_Resolution": "3840x2400",
      "Touch_Screen": "Yes",
      "Display_Refresh_Rate": "60Hz",
      "Brightness": "500 nits",
      "camera": "720p HD",
      "Battery_Capacity": "86WHr",
      "Backup_Time": "Up to 12 hours",
      "power_adapter": "130W",
      "Warranty": "1 Year",
      "price": 2299,
      "description_1": "The Dell XPS 15 is a powerful ultrabook that blends performance with stunning visuals for creators and gamers alike.",
      "description_2": "With its vibrant OLED display and robust graphics, it excels in both productivity and gaming."
    },
    {
      "id": 10,
      "image_url": "https://asset.msi.com/resize/image/global/product/product_9_20200309135719_5e65dabf900d7.png62405b38c58fe0f07fcef2367d8a9ba1/1024.png",
      "Brand": "MSI",
      "Model": "GS66 Stealth",
      "Laptop_Series": "Gaming",
      "Processor_Brand": "Intel",
      "Processor_Type": "Core i7",
      "Processor_Generation": "11th",
      "CPU_Cache": "12MB",
      "color": "Black",
      "ram": "32GB",
      "RAM_Type": "DDR4",
      "Max_RAM_Support": "64GB",
      "Storage": "1TB SSD",
      "Installed_SSD_Type": "NVMe",
      "Installed_HDD_Type": "None",
      "Storage_Upgrade": "Yes, up to 2TB SSD",
      "Graphics_Chipset": "NVIDIA GeForce RTX 3070",
      "Graphics_Memory": "8GB",
      "Display_Size": "15.6 inch",
      "Display_Type": "IPS",
      "Display_Resolution": "1920x1080",
      "Touch_Screen": "No",
      "Display_Refresh_Rate": "240Hz",
      "Brightness": "300 nits",
      "camera": "720p HD",
      "Battery_Capacity": "99WHr",
      "Backup_Time": "Up to 8 hours",
      "power_adapter": "230W",
      "Warranty": "1 Year",
      "price": 2499,
      "description_1": "The MSI GS66 Stealth offers high performance in a sleek and portable design, perfect for gamers on the go.",
      "description_2": "With its ultra-fast display and powerful graphics, it excels in demanding gaming scenarios."
    },
    {
      "id": 11,
      "image_url": "https://shop.samsung.com/ie/images/products/28117/19677/2000x2000/NP950QDB-KB4UK.webp",
      "Brand": "Samsung",
      "Model": "Galaxy Book Pro",
      "Laptop_Series": "Ultrabook",
      "Processor_Brand": "Intel",
      "Processor_Type": "Core i7",
      "Processor_Generation": "12th",
      "CPU_Cache": "12MB",
      "color": "Mystic Silver",
      "ram": "16GB",
      "RAM_Type": "LPDDR4X",
      "Max_RAM_Support": "32GB",
      "Storage": "512GB SSD",
      "Installed_SSD_Type": "NVMe",
      "Installed_HDD_Type": "None",
      "Storage_Upgrade": "Yes, up to 1TB SSD",
      "Graphics_Chipset": "Intel Iris Xe",
      "Graphics_Memory": "Integrated",
      "Display_Size": "13.3 inch",
      "Display_Type": "AMOLED",
      "Display_Resolution": "1920x1080",
      "Touch_Screen": "Yes",
      "Display_Refresh_Rate": "60Hz",
      "Brightness": "400 nits",
      "camera": "720p HD",
      "Battery_Capacity": "63WHr",
      "Backup_Time": "Up to 20 hours",
      "power_adapter": "65W USB-C",
      "Warranty": "1 Year",
      "price": 1599,
      "description_1": "The Samsung Galaxy Book Pro 360 is a versatile ultrabook with a stunning AMOLED display and long battery life.",
      "description_2": "Perfect for both work and play, it features a sleek design and powerful performance."
    },
    {
      "id": 12,
      "image_url": "https://ryans.com/storage/products/main/razer-blade-15-base-intel-core-i7-10750h-156-11619323359.webp",
      "Brand": "Razer",
      "Model": "Blade 15",
      "Laptop_Series": "Gaming",
      "Processor_Brand": "Intel",
      "Processor_Type": "Core i7",
      "Processor_Generation": "13th",
      "CPU_Cache": "12MB",
      "color": "Black",
      "ram": "16GB",
      "RAM_Type": "DDR4",
      "Max_RAM_Support": "64GB",
      "Storage": "1TB SSD",
      "Installed_SSD_Type": "NVMe",
      "Installed_HDD_Type": "None",
      "Storage_Upgrade": "Yes, up to 4TB SSD",
      "Graphics_Chipset": "NVIDIA GeForce RTX 3070",
      "Graphics_Memory": "8GB",
      "Display_Size": "15.6 inch",
      "Display_Type": "OLED",
      "Display_Resolution": "3840x2160",
      "Touch_Screen": "Yes",
      "Display_Refresh_Rate": "144Hz",
      "Brightness": "400 nits",
      "camera": "720p HD",
      "Battery_Capacity": "80WHr",
      "Backup_Time": "Up to 7 hours",
      "power_adapter": "230W",
      "Warranty": "1 Year",
      "price": 2499,
      "description_1": "The Razer Blade 15 combines high performance and elegant design for gamers who demand the best.",
      "description_2": "With a stunning 4K OLED display and powerful graphics, it’s perfect for both gaming and creative work."
    },
    {
      "id": 13,
      "image_url": "https://ryans.com/storage/products/main/hp-spectre-x360-convertible-14-ea1590tu-intel-41711168510.webp",
      "Brand": "HP",
      "Model": "Spectre x360",
      "Laptop_Series": "Ultrabook",
      "Processor_Brand": "Intel",
      "Processor_Type": "Core i7",
      "Processor_Generation": "11th",
      "CPU_Cache": "12MB",
      "color": "Nightfall Black",
      "ram": "16GB",
      "RAM_Type": "LPDDR4X",
      "Max_RAM_Support": "32GB",
      "Storage": "1TB SSD",
      "Installed_SSD_Type": "NVMe",
      "Installed_HDD_Type": "None",
      "Storage_Upgrade": "Yes, up to 2TB SSD",
      "Graphics_Chipset": "Intel Iris Xe",
      "Graphics_Memory": "Integrated",
      "Display_Size": "13.3 inch",
      "Display_Type": "OLED",
      "Display_Resolution": "3000x2000",
      "Touch_Screen": "Yes",
      "Display_Refresh_Rate": "60Hz",
      "Brightness": "400 nits",
      "camera": "720p HD",
      "Battery_Capacity": "60WHr",
      "Backup_Time": "Up to 10 hours",
      "power_adapter": "65W USB-C",
      "Warranty": "1 Year",
      "price": 1799,
      "description_1": "The HP Spectre x360 is a luxurious ultrabook designed for users who value performance and aesthetics.",
      "description_2": "With a stunning 4K OLED display and convertible design, it's perfect for both work and play."
    },
    {
      "id": 14,
      "image_url": "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/alienware-notebooks/alienware-x17-r2/media-gallery/updated/laptop-alienware-x17-r2-gray-gallery-1.psd?fmt=png-alpha&pscan=auto&scl=1&hei=402&wid=360&qlt=100,1&resMode=sharp2&size=360,402&chrss=full",
      "Brand": "Alienware",
      "Model": "X17 R2",
      "Laptop_Series": "Gaming",
      "Processor_Brand": "Intel",
      "Processor_Type": "Core i9",
      "Processor_Generation": "12th",
      "CPU_Cache": "30MB",
      "color": "Lunar Light",
      "ram": "32GB",
      "RAM_Type": "DDR5",
      "Max_RAM_Support": "64GB",
      "Storage": "2TB SSD",
      "Installed_SSD_Type": "NVMe",
      "Installed_HDD_Type": "None",
      "Storage_Upgrade": "Yes, up to 4TB SSD",
      "Graphics_Chipset": "NVIDIA GeForce RTX 3080",
      "Graphics_Memory": "10GB",
      "Display_Size": "17.3 inch",
      "Display_Type": "IPS",
      "Display_Resolution": "2560x1440",
      "Touch_Screen": "Yes",
      "Display_Refresh_Rate": "165Hz",
      "Brightness": "400 nits",
      "camera": "720p HD",
      "Battery_Capacity": "87WHr",
      "Backup_Time": "Up to 5 hours",
      "power_adapter": "330W",
      "Warranty": "1 Year",
      "price": 3299,
      "description_1": "The Alienware X17 R2 is a high-performance gaming laptop designed for serious gamers seeking the best.",
      "description_2": "With cutting-edge hardware and a stunning display, it offers an unparalleled gaming experience."
    },
    {
        "id": 15,
        "image_url": "https://computermania-bd.b-cdn.net/wp-content/uploads/00013-ASUS-ROG-Strix-5.jpg",
        "Brand": "Asus",
        "Model": "ROG Strix G15",
        "Laptop_Series": "ROG Strix",
        "Processor_Brand": "AMD",
        "Processor_Type": "Ryzen 9",
        "Processor_Generation": "5th Gen",
        "Processor_Core": "Octa-Core",
        "Performance_Cores": 8,
        "CPU_Cache": "16MB",
        "color": "Eclipse Gray",
        "ram": "16GB",
        "RAM_Type": "DDR4",
        "Total_RAM_Slot": 2,
        "Max_RAM_Support": "32GB",
        "Storage": "1TB SSD",
        "Installed_SSD_Type": "NVMe",
        "Installed_HDD_Type": "None",
        "Storage_Upgrade": "Yes, up to 2TB SSD",
        "Graphics_Chipset": "NVIDIA GeForce RTX 3060",
        "Graphics_Memory": "6GB",
        "Display_Size": "15.6 inch",
        "Display_Type": "LED",
        "Panel_Type": "IPS",
        "Display_Resolution": "1920x1080",
        "Touch_Screen": "No",
        "Display_Refresh_Rate": "144Hz",
        "Brightness": "300 nits",
        "Ports_and_Slots": "3x USB 3.2 Gen 1, 1x USB-C, 1x HDMI 2.0b, 1x Ethernet, 1x 3.5mm Audio Jack",
        "camera": "None",
        "speaker": "Stereo speakers with Dolby Atmos",
        "Battery": "4-cell",
        "Battery_Capacity": "90WHr",
        "Backup_Time": "Up to 12 hours",
        "power_adapter": "240W",
        "Warranty": "2 Years",
        "price": 1999,
        "description_1": "Asus ROG Strix G15 is a gaming powerhouse designed for high performance with AMD Ryzen 9 and NVIDIA RTX graphics for a smooth gaming experience.",
        "description_2": "This laptop is perfect for gamers and power users, featuring a high refresh rate display and fast SSD storage for quick load times and responsive gameplay."
    },
    {
      "id": 16,
      "image_url": "https://static.gigabyte.com/StaticFile/Image/Global/28f316f290c445e5074f643be4303464/Product/24399/Png",
      "Brand": "Gigabyte",
      "Model": "AORUS 15G",
      "Laptop_Series": "Gaming",
      "Processor_Brand": "Intel",
      "Processor_Type": "Core i7",
      "Processor_Generation": "11th",
      "CPU_Cache": "12MB",
      "color": "Black",
      "ram": "16GB",
      "RAM_Type": "DDR4",
      "Max_RAM_Support": "64GB",
      "Storage": "1TB SSD",
      "Installed_SSD_Type": "NVMe",
      "Installed_HDD_Type": "None",
      "Storage_Upgrade": "Yes, up to 2TB SSD",
      "Graphics_Chipset": "NVIDIA GeForce RTX 3070",
      "Graphics_Memory": "8GB",
      "Display_Size": "15.6 inch",
      "Display_Type": "IPS",
      "Display_Resolution": "1920x1080",
      "Touch_Screen": "No",
      "Display_Refresh_Rate": "240Hz",
      "Brightness": "300 nits",
      "camera": "720p HD",
      "Battery_Capacity": "99WHr",
      "Backup_Time": "Up to 8 hours",
      "power_adapter": "230W",
      "Warranty": "1 Year",
      "price": 2299,
      "description_1": "The Gigabyte AORUS 15G is designed for gamers who demand high performance in a sleek and portable design.",
      "description_2": "With a fast display and powerful GPU, it's ideal for competitive gaming."
    },
    {
        "id": 21,
        "image_url": "https://laptoptitan.vn/wp-content/uploads/2022/01/Razer-Blade-15-Mercury-White-Base-01.jpg",
        "Brand": "Razer",
        "Model": "Blade 15 Base",
        "Laptop_Series": "Gaming",
        "Processor_Brand": "Intel",
        "Processor_Type": "Core i7",
        "Processor_Generation": "12th",
        "CPU_Cache": "24MB",
        "color": "White",
        "ram": "16GB",
        "RAM_Type": "DDR5",
        "Max_RAM_Support": "32GB",
        "Storage": "1TB SSD",
        "Installed_SSD_Type": "NVMe",
        "Installed_HDD_Type": "None",
        "Storage_Upgrade": "Yes, up to 2TB SSD",
        "Graphics_Chipset": "NVIDIA GeForce RTX 3060",
        "Graphics_Memory": "6GB GDDR6",
        "Display_Size": "15.6 inch",
        "Display_Type": "OLED",
        "Display_Resolution": "1920x1080",
        "Touch_Screen": "No",
        "Display_Refresh_Rate": "144Hz",
        "Brightness": "300 nits",
        "camera": "720p HD",
        "Battery_Capacity": "80WHr",
        "Backup_Time": "Up to 6 hours",
        "power_adapter": "230W",
        "Warranty": "1 Year",
        "price": 1999,
        "description_1": "The Razer Blade 15 Base is a powerful gaming laptop designed for high-performance gaming and multitasking.",
        "description_2": "Featuring a stunning OLED display and advanced cooling technology, it ensures an immersive gaming experience."
    },
    {
      "id": 18,
      "image_url": "https://www.asus.com/media/global/gallery/1qq8vmq0mcqfgefj_setting_xxx_0_90_end_2000.png",
      "Brand": "Asus",
      "Model": "VivoBook 15",
      "Laptop_Series": "Ultrabook",
      "Processor_Brand": "AMD",
      "Processor_Type": "Ryzen 5",
      "Processor_Generation": "5500U",
      "CPU_Cache": "8MB",
      "color": "Slate Gray",
      "ram": "8GB",
      "RAM_Type": "DDR4",
      "Max_RAM_Support": "16GB",
      "Storage": "512GB SSD",
      "Installed_SSD_Type": "NVMe",
      "Installed_HDD_Type": "None",
      "Storage_Upgrade": "Yes, up to 1TB SSD",
      "Graphics_Chipset": "Integrated Radeon Graphics",
      "Graphics_Memory": "Integrated",
      "Display_Size": "15.6 inch",
      "Display_Type": "IPS",
      "Display_Resolution": "1920x1080",
      "Touch_Screen": "No",
      "Display_Refresh_Rate": "60Hz",
      "Brightness": "250 nits",
      "camera": "720p HD",
      "Battery_Capacity": "42WHr",
      "Backup_Time": "Up to 6 hours",
      "power_adapter": "65W",
      "Warranty": "1 Year",
      "price": 649,
      "description_1": "The Asus VivoBook 15 offers a perfect blend of performance and portability at an affordable price.",
      "description_2": "Ideal for everyday tasks and entertainment, it features a sleek design and vibrant display."
    },
    {
      "id": 19,
      "image_url": "https://singerbd.com/media/catalog/product/cache/482df9e5219860e2561c4ec99993e0ed/3/5/3520_core_i7.jpg",
      "Brand": "Dell",
      "Model": "Inspiron 15",
      "Laptop_Series": "Ultrabook",
      "Processor_Brand": "AMD",
    "Processor_Type": "Ryzen 5",
    "Processor_Generation": "5th",
      "CPU_Cache": "8MB",
      "color": "Platinum Silver",
      "ram": "8GB",
      "RAM_Type": "DDR4",
      "Max_RAM_Support": "16GB",
      "Storage": "256GB SSD",
      "Installed_SSD_Type": "NVMe",
      "Installed_HDD_Type": "None",
      "Storage_Upgrade": "Yes, up to 1TB SSD",
      "Graphics_Chipset": "Intel Iris Xe",
      "Graphics_Memory": "Integrated",
      "Display_Size": "15.6 inch",
      "Display_Type": "IPS",
      "Display_Resolution": "1920x1080",
      "Touch_Screen": "No",
      "Display_Refresh_Rate": "60Hz",
      "Brightness": "250 nits",
      "camera": "720p HD",
      "Battery_Capacity": "42WHr",
      "Backup_Time": "Up to 7 hours",
      "power_adapter": "65W",
      "Warranty": "1 Year",
      "price": 579,
      "description_1": "The Dell Inspiron 15 is a reliable and affordable ultrabook for students and professionals alike.",
      "description_2": "With a sleek design and solid performance, it's perfect for daily use."
    },
    {
      "id": 20,
      "image_url": "https://th-media.apjonlinecdn.com/catalog/product/cache/b3b166914d87ce343d4dc5ec5117b502/7/Z/7Z0A8PA-1_T1679051830.png",
      "Brand": "HP",
      "Model": "Pavilion 15",
      "Laptop_Series": "Ultrabook",
      "Processor_Brand": "Intel",
      "Processor_Type": "Core i5",
      "Processor_Generation": "11th",
      "CPU_Cache": "8MB",
      "color": "Silver",
      "ram": "8GB",
      "RAM_Type": "DDR4",
      "Max_RAM_Support": "16GB",
      "Storage": "512GB SSD",
      "Installed_SSD_Type": "NVMe",
      "Installed_HDD_Type": "None",
      "Storage_Upgrade": "Yes, up to 1TB SSD",
      "Graphics_Chipset": "Intel Iris Xe",
      "Graphics_Memory": "Integrated",
      "Display_Size": "15.6 inch",
      "Display_Type": "IPS",
      "Display_Resolution": "1920x1080",
      "Touch_Screen": "No",
      "Display_Refresh_Rate": "60Hz",
      "Brightness": "250 nits",
      "camera": "720p HD",
      "Battery_Capacity": "43WHr",
      "Backup_Time": "Up to 8 hours",
      "power_adapter": "65W",
      "Warranty": "1 Year",
      "price": 649,
      "description_1": "The HP Pavilion 15 is a stylish ultrabook that balances performance and portability.",
      "description_2": "Perfect for everyday tasks, it offers a vibrant display and long battery life."
    },
    {
        "id": 21,
        "image_url": "https://www.example.com/surface_pro.jpg",
        "Brand": "Microsoft",
        "Model": "Surface Pro 9",
        "Laptop_Series": "2-in-1",
        "Processor_Brand": "Intel",
        "Processor_Type": "Core i7",
        "Processor_Generation": "12th",
        "CPU_Cache": "12MB",
        "color": "Platinum",
        "ram": "16GB",
        "RAM_Type": "LPDDR5",
        "Max_RAM_Support": "32GB",
        "Storage": "512GB SSD",
        "Installed_SSD_Type": "NVMe",
        "Installed_HDD_Type": "None",
        "Storage_Upgrade": "Yes, up to 1TB SSD",
        "Graphics_Chipset": "Intel Iris Xe",
        "Graphics_Memory": "Integrated",
        "Display_Size": "13 inch",
        "Display_Type": "PixelSense",
        "Display_Resolution": "2880x1920",
        "Touch_Screen": "Yes",
        "Display_Refresh_Rate": "120Hz",
        "Brightness": "450 nits",
        "camera": "720p HD",
        "Battery_Capacity": "51.5WHr",
        "Backup_Time": "Up to 16 hours",
        "power_adapter": "65W USB-C",
        "Warranty": "1 Year",
        "price": 1399,
        "description_1": "The Microsoft Surface Pro 9 is a versatile 2-in-1 device that combines the power of a laptop with the portability of a tablet.",
        "description_2": "Ideal for creatives and professionals, featuring a high-resolution display and excellent battery life."
      },      
      {
        "id": 22,
        "image_url": "https://m.media-amazon.com/images/I/61f0L+DV-YL._AC_UF1000,1000_QL80_.jpg",
        "Brand": "HP",
        "Model": "Envy x360",
        "Laptop_Series": "Ultrabook",
        "Processor_Brand": "AMD",
        "Processor_Type": "Ryzen 7",
        "Processor_Generation": "5th",
        "CPU_Cache": "16MB",
        "color": "Nightfall Black",
        "ram": "16GB",
        "RAM_Type": "DDR4",
        "Max_RAM_Support": "32GB",
        "Storage": "512GB SSD",
        "Installed_SSD_Type": "NVMe",
        "Installed_HDD_Type": "None",
        "Storage_Upgrade": "Yes, up to 1TB SSD",
        "Graphics_Chipset": "AMD Radeon",
        "Graphics_Memory": "Integrated",
        "Display_Size": "15.6 inch",
        "Display_Type": "LED",
        "Display_Resolution": "1920x1080",
        "Touch_Screen": "Yes",
        "Display_Refresh_Rate": "60Hz",
        "Brightness": "400 nits",
        "camera": "720p HD",
        "Battery_Capacity": "51WHr",
        "Backup_Time": "Up to 11 hours",
        "power_adapter": "65W USB-C",
        "Warranty": "1 Year",
        "price": 1299,
        "description_1": "HP Envy x360 is a versatile 2-in-1 laptop with powerful performance and a vibrant touchscreen, ideal for creators and professionals.",
        "description_2": "The Ryzen 7 processor and flexible design make it perfect for multitasking, whether for work or entertainment."
      },
      {
        "id": 23,
        "image_url": "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/g-series/g15-5521-se/media-gallery/g15-5521-se-bk-rgbkb-115w/notebook-g-15-5521-gallery-1.psd?fmt=pjpg&pscan=auto&scl=1&wid=4438&hei=3618&qlt=100,1&resMode=sharp2&size=4438,3618&chrss=full&imwidth=5000",
        "Brand": "Dell",
        "Model": "G15",
        "Laptop_Series": "Gaming",
        "Processor_Brand": "Intel",
        "Processor_Type": "Core i5",
        "Processor_Generation": "12th Gen",
        "CPU_Cache": "18MB",
        "color": "Dark Shadow Grey",
        "ram": "8GB",
        "RAM_Type": "DDR4",
        "Max_RAM_Support": "32GB",
        "Storage": "256GB SSD",
        "Installed_SSD_Type": "PCIe",
        "Installed_HDD_Type": "None",
        "Storage_Upgrade": "Yes, up to 1TB SSD",
        "Graphics_Chipset": "NVIDIA RTX 3050",
        "Graphics_Memory": "4GB",
        "Display_Size": "15.6 inch",
        "Display_Type": "LED",
        "Display_Resolution": "1920x1080",
        "Touch_Screen": "No",
        "Display_Refresh_Rate": "120Hz",
        "Brightness": "250 nits",
        "camera": "720p HD",
        "Battery_Capacity": "56WHr",
        "Backup_Time": "Up to 9 hours",
        "power_adapter": "130W",
        "Warranty": "1 Year",
        "price": 899,
        "description_1": "Dell G15 is a robust gaming laptop, equipped with RTX graphics and a fast refresh rate for seamless gameplay.",
        "description_2": "This laptop offers excellent value for gamers looking for a balance between performance and affordability."
      },
      {
        "id": 24,
        "image_url": "https://www.atacadoconnect.com/imagem/notebooks/notebook-samsung-galaxy-book-odyssey-np762xda-xa1us-15-6-intel-core-i7-11600h-512gb-ssd-8gb-ram-nvidia-geforce-rtx-3050-ti-preto/2/204586.jpg?pfdrid_c=true",
        "Brand": "Samsung",
        "Model": "Galaxy Book Odyssey",
        "Laptop_Series": "Gaming",
        "Processor_Brand": "Intel",
        "Processor_Type": "Core i5",
        "Processor_Generation": "11th",
        "CPU_Cache": "12MB",
        "color": "Mystic Navy",
        "ram": "16GB",
        "RAM_Type": "DDR4",
        "Max_RAM_Support": "32GB",
        "Storage": "1TB SSD",
        "Installed_SSD_Type": "NVMe",
        "Installed_HDD_Type": "None",
        "Storage_Upgrade": "Yes, up to 2TB SSD",
        "Graphics_Chipset": "NVIDIA GeForce RTX 3050",
        "Graphics_Memory": "4GB GDDR6",
        "Display_Size": "15.6 inch",
        "Display_Type": "FHD",
        "Display_Resolution": "1920x1080",
        "Touch_Screen": "No",
        "Display_Refresh_Rate": "60Hz",
        "Brightness": "300 nits",
        "camera": "720p HD",
        "Battery_Capacity": "76WHr",
        "Backup_Time": "Up to 10 hours",
        "power_adapter": "135W",
        "Warranty": "1 Year",
        "price": 1499,
        "description_1": "The Samsung Galaxy Book Odyssey is a versatile laptop perfect for both gaming and productivity.",
        "description_2": "With a stylish design and powerful specs, it's an excellent choice for work and play."
      },
      {
        "id": 25,
        "image_url": "https://ryans.com/storage/products/main/microsoft-surface-laptop-5-intel-core-i7-1265u-11697279015.webp",
        "Brand": "Microsoft",
        "Model": "Surface Laptop 5",
        "Laptop_Series": "Ultrabook",
        "Processor_Brand": "Intel",
        "Processor_Type": "Core i5",
        "Processor_Generation": "11th",
        "CPU_Cache": "12MB",
        "color": "Matte Black",
        "ram": "16GB",
        "RAM_Type": "LPDDR5",
        "Max_RAM_Support": "32GB",
        "Storage": "1TB SSD",
        "Installed_SSD_Type": "NVMe",
        "Installed_HDD_Type": "None",
        "Storage_Upgrade": "Yes, up to 1TB SSD",
        "Graphics_Chipset": "Intel Iris Xe",
        "Graphics_Memory": "Integrated",
        "Display_Size": "13.5 inch",
        "Display_Type": "PixelSense",
        "Display_Resolution": "2256x1504",
        "Touch_Screen": "Yes",
        "Display_Refresh_Rate": "60Hz",
        "Brightness": "400 nits",
        "camera": "720p HD",
        "Battery_Capacity": "47.4WHr",
        "Backup_Time": "Up to 15 hours",
        "power_adapter": "65W USB-C",
        "Warranty": "1 Year",
        "price": 1799,
        "description_1": "The Microsoft Surface Laptop 5 delivers high performance with a sleek and elegant design.",
        "description_2": "Perfect for professionals on the go, offering a stunning display and exceptional battery life."
      },
      {
        "id": 26,
        "image_url": "https://gadgetnovabd.com/wp-content/uploads/2023/05/aec50545-6c46-4829-b957-401ccec69996-700x525.png",
        "Brand": "HP",
        "Model": "Victus 16",
        "Laptop_Series": "Gaming",
        "Processor_Brand": "Intel",
        "Processor_Type": "Core i7",
        "Processor_Generation": "13th",
        "CPU_Cache": "24MB",
        "color": "Mica Silver",
        "ram": "16GB",
        "RAM_Type": "DDR4",
        "Max_RAM_Support": "32GB",
        "Storage": "1TB SSD",
        "Installed_SSD_Type": "NVMe",
        "Installed_HDD_Type": "None",
        "Storage_Upgrade": "Yes, up to 2TB SSD",
        "Graphics_Chipset": "NVIDIA GeForce RTX 3060",
        "Graphics_Memory": "6GB GDDR6",
        "Display_Size": "16.1 inch",
        "Display_Type": "IPS",
        "Display_Resolution": "1920x1080",
        "Touch_Screen": "No",
        "Display_Refresh_Rate": "144Hz",
        "Brightness": "300 nits",
        "camera": "720p HD",
        "Battery_Capacity": "70WHr",
        "Backup_Time": "Up to 8 hours",
        "power_adapter": "200W",
        "Warranty": "1 Year",
        "price": 1299,
        "description_1": "The HP Victus 16 combines powerful performance with a sleek design, perfect for gaming and multitasking.",
        "description_2": "With an Intel Core i7 and NVIDIA GeForce RTX graphics, this laptop handles demanding games and applications with ease."
      },
      {
        "id": 27,
        "image_url": "https://ryans.com/storage/products/main/msi-prestige-14-a11sc-11th-gen-intel-core-i7-11629357054.webp",
        "Brand": "MSI",
        "Model": "Prestige 14",
        "Laptop_Series": "Ultrabook",
        "Processor_Brand": "Intel",
        "Processor_Type": "Core i7",
        "Processor_Generation": "13th",
        "CPU_Cache": "18MB",
        "color": "Carbon Gray",
        "ram": "16GB",
        "RAM_Type": "LPDDR5",
        "Max_RAM_Support": "32GB",
        "Storage": "1TB SSD",
        "Installed_SSD_Type": "NVMe",
        "Installed_HDD_Type": "None",
        "Storage_Upgrade": "Yes, up to 2TB SSD",
        "Graphics_Chipset": "NVIDIA GeForce RTX 3050",
        "Graphics_Memory": "4GB GDDR6",
        "Display_Size": "14 inch",
        "Display_Type": "IPS",
        "Display_Resolution": "2880x1800",
        "Touch_Screen": "Yes",
        "Display_Refresh_Rate": "60Hz",
        "Brightness": "400 nits",
        "camera": "720p HD",
        "Battery_Capacity": "50WHr",
        "Backup_Time": "Up to 10 hours",
        "power_adapter": "65W USB-C",
        "Warranty": "1 Year",
        "price": 1499,
        "description_1": "The MSI Prestige 14 is an elegant ultrabook designed for professionals seeking performance and portability.",
        "description_2": "Featuring a vibrant display and powerful components, it's perfect for creative work and everyday tasks."
      },
      {
        "id": 28,
        "image_url": "https://p3-ofp.static.pub/fes/cms/2023/02/03/02x5fu01g7gx92z6n4rq7lzieewbxg228212.png",
        "Brand": "Lenovo",
        "Model": "ThinkBook 14s Yoga",
        "Laptop_Series": "Ultrabook",
        "Processor_Brand": "Intel",
        "Processor_Type": "Core i5",
        "Processor_Generation": "12th",
        "CPU_Cache": "12MB",
        "color": "Mineral Gray",
        "ram": "16GB",
        "RAM_Type": "LPDDR4X",
        "Max_RAM_Support": "16GB",
        "Storage": "512GB SSD",
        "Installed_SSD_Type": "NVMe",
        "Installed_HDD_Type": "None",
        "Storage_Upgrade": "Yes, up to 1TB SSD",
        "Graphics_Chipset": "Intel Iris Xe",
        "Graphics_Memory": "Integrated",
        "Display_Size": "14 inch",
        "Display_Type": "IPS",
        "Display_Resolution": "1920x1080",
        "Touch_Screen": "Yes",
        "Display_Refresh_Rate": "60Hz",
        "Brightness": "300 nits",
        "camera": "720p HD",
        "Battery_Capacity": "60WHr",
        "Backup_Time": "Up to 12 hours",
        "power_adapter": "65W USB-C",
        "Warranty": "1 Year",
        "price": 1299,
        "description_1": "The Lenovo ThinkBook 14s Yoga is a versatile ultrabook with a 2-in-1 design, perfect for business professionals on the go.",
        "description_2": "Offering a touchscreen display, powerful Intel processor, and long battery life, this ultrabook is built for productivity and flexibility."
      },
      {
        "id": 29,
        "image_url": "https://m.media-amazon.com/images/I/61k3I9unmxL._AC_UF894,1000_QL80_.jpg",
        "Brand": "Gigabyte",
        "Model": "U4 UD",
        "Laptop_Series": "Ultrabook",
        "Processor_Brand": "Intel",
        "Processor_Type": "Core i7",
        "Processor_Generation": "11th",
        "CPU_Cache": "12MB",
        "color": "Gray",
        "ram": "16GB",
        "RAM_Type": "DDR4",
        "Max_RAM_Support": "32GB",
        "Storage": "512GB SSD",
        "Installed_SSD_Type": "NVMe",
        "Installed_HDD_Type": "None",
        "Storage_Upgrade": "Yes, up to 1TB SSD",
        "Graphics_Chipset": "Intel Iris Xe",
        "Graphics_Memory": "Integrated",
        "Display_Size": "14 inch",
        "Display_Type": "IPS",
        "Display_Resolution": "1920x1080",
        "Touch_Screen": "No",
        "Display_Refresh_Rate": "60Hz",
        "Brightness": "300 nits",
        "camera": "720p HD",
        "Battery_Capacity": "50WHr",
        "Backup_Time": "Up to 10 hours",
        "power_adapter": "65W USB-C",
        "Warranty": "1 Year",
        "price": 1099,
        "description_1": "The Gigabyte U4 UD is a lightweight ultrabook designed for professionals seeking portability and performance.",
        "description_2": "Equipped with an Intel i7 processor and a vibrant 14-inch display, it offers an excellent balance of power and mobility."
      },
      {
        "id": 30,
        "image_url": "https://ryans.com/storage/products/main/asus-zenbook-14-um425qa-amd-ryzen-7-5800h-8gb-ram-11722665742.webp",
        "Brand": "ASUS",
        "Model": "ZenBook 14",
        "Laptop_Series": "Ultrabook",
        "Processor_Brand": "AMD",
    "Processor_Type": "Ryzen 7",
    "Processor_Generation": "5th",
        "CPU_Cache": "12MB",
        "color": "Pine Grey",
        "ram": "16GB",
        "RAM_Type": "LPDDR4X",
        "Max_RAM_Support": "16GB",
        "Storage": "1TB SSD",
        "Installed_SSD_Type": "NVMe",
        "Installed_HDD_Type": "None",
        "Storage_Upgrade": "Yes, up to 2TB SSD",
        "Graphics_Chipset": "Intel Iris Xe",
        "Graphics_Memory": "Integrated",
        "Display_Size": "14 inch",
        "Display_Type": "IPS",
        "Display_Resolution": "1920x1080",
        "Touch_Screen": "No",
        "Display_Refresh_Rate": "60Hz",
        "Brightness": "400 nits",
        "camera": "720p HD",
        "Battery_Capacity": "67WHr",
        "Backup_Time": "Up to 16 hours",
        "power_adapter": "65W USB-C",
        "Warranty": "1 Year",
        "price": 1399,
        "description_1": "The ASUS ZenBook 14 is a slim and portable ultrabook featuring Intel's 12th Gen Core i7 processor, perfect for professionals on the move.",
        "description_2": "With an impressive display, fast performance, and long battery life, it’s a great choice for productivity and entertainment."
      }
      


      
      
      
  ]
  
  export default laptopSpecs